---
abstract: 'Perl extension for creating standalone Vkontakte API applications'
author:
  - 'Krylov Ivan <krylov.r00t@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-VKontakte-Standalone
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  JSON: 0
  URI: 0
  WWW::Mechanize: 0
version: 0.18_95
